[project]
name = "pyrig-codecov"
version = "3.16.55"
description = "A pyrig plugin that integrates codecov."
readme = "README.md"
requires-python = ">=3.12"
license = "MIT"
license-files = [
  "LICENSE",
]
authors = [
  { name = "Winipedia", email = "winipedia@gmx.de" },
]
maintainers = [
  { name = "Winipedia", email = "winipedia@gmx.de" },
]
keywords = [
  "pyrig",
]
classifiers = [
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Typing :: Typed",
]
dependencies = [
  "pyrig>=18.10.1",
  "pyrig-runtime",
]

[project.urls]
Changelog = "https://github.com/Winipedia/pyrig-codecov/releases"
Documentation = "https://Winipedia.github.io/pyrig-codecov"
Homepage = "https://github.com/Winipedia/pyrig-codecov"
Issues = "https://github.com/Winipedia/pyrig-codecov/issues"
Source = "https://github.com/Winipedia/pyrig-codecov"

[project.scripts]
pyrig-codecov = "pyrig_runtime.rig.cli.main:main"

[dependency-groups]
dev = [
  "bandit",
  "deptry",
  "detect-secrets",
  "mkdocstrings[python]",
  "pre-commit-hooks",
  "prek",
  "pyrig",
  "pyrig-fixtures>=2.15.0",
  "pyrig-pypi>=3.5.0",
  "pytest",
  "pytest-cov",
  "pytest-randomly",
  "pytest-xdist>=3.8.0",
  "ruff",
  "rumdl",
  "ryl",
  "shellcheck-py",
  "shfmt-py",
  "tombi",
  "ty",
  "typos",
  "zensical>=0.0.52",
]

[build-system]
requires = [
  "uv-build",
]
build-backend = "uv_build"

[tool.deptry]
root = "src"

[tool.deptry.per_rule_ignores]
DEP002 = [
  "pyrig-runtime",
]

[tool.pytest]
addopts = [
  "--cov-branch",
  "--cov-fail-under=100",
  "--cov-fail-under=90",
  "--cov-report=term-missing:skip-covered",
  "--cov-report=xml",
  "--cov=pyrig_codecov",
  "--dist=worksteal",
  "--numprocesses=auto",
  "--report-chars=a",
]
filterwarnings = [
  "error",
]
strict = true
testpaths = [
  "tests",
]

[tool.ruff.format]
docstring-code-format = true

[tool.ruff.lint]
ignore = [
  "CPY001",
]
select = [
  "ALL",
]

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = [
  "S101",
]

[tool.ruff.lint.pydocstyle]
convention = "google"
